### ISSUE TITLE
Falta una prueba y funcionalidad

### ISSUE THREAD

**Issue by evolentini** [mauriciobarroso/CESE-10Co2019_TSSE---TP3#1]
https://github.com/mauriciobarroso/CESE-10Co2019_TSSE---TP3/blob/af6a939df881bc86322c4effe30382b7dc854f4f/test/test_leds.c#L89-L97

Falta probar que la función informa correctamente el estado de un led apagado.

https://github.com/mauriciobarroso/CESE-10Co2019_TSSE---TP3/blob/af6a939df881bc86322c4effe30382b7dc854f4f/src/leds.c#L55-L62

Esto esa correcto, pero había que implementar la funcionalidad completa, y si hacia falta agregar test agregarlos...

**Comment by mauriciobarroso** [comment]
Corregidos Esteban, saludos.
